### ISSUE TITLE
Support for Expo 52 / React Native 76

### ISSUE THREAD

**Issue by kmye** [lodev09/react-native-true-sheet#105]
Hi!

I tried to upgrade to Expo 52 but seems like this library doesn't support the new architecture yet. Any plans on this?

**Comment by ReactorCSA** [comment]
As for me, the TrueSheet is partially working. The Sheet appears, but ScrollView does not work. Tried using from 'react-native', 'react-native-reanimated', RNHG, but unfortunately, none of them seem to be working.
Tested on Android, react-native 76 with new Arch.
On paper the same implementation of ScrollView works fine

**Comment by kmye** [comment]
yes, i have the same problem, none of the Pressable component inside the Sheet works..

> As for me, the TrueSheet is partially working. The Sheet appears, but ScrollView does not work. Tried using from 'react-native', 'react-native-reanimated', RNHG, but unfortunately, none of them seem to be working. Tested on Android, react-native 76 with new Arch. On paper the same implementation of ScrollView works fine

**Comment by lodev09** [comment]
Yes, Expo 52 (new arch) it's currently work in progress 
https://github.com/lodev09/react-native-true-sheet/discussions/20
