### ISSUE TITLE
[BUG][IOS] Crash when trying to open the sheet

### ISSUE THREAD

**Issue by KristijanKocev** [lodev09/react-native-true-sheet#109]
This happens rarely but enough that it is noticeable and our only source of crashes recently, maybe once every few days with daily usage.
I could not catch or reproduce it in dev, but here are the crash logs from Testflight which might help you identify the issue.
So far it has only happened on ios and never on android.
<img width="797" alt="Screenshot 2024-11-26 at 10 31 43" src="https://github.com/user-attachments/assets/ff45fb46-bcc0-45ac-9861-4e80e6134476">

The crash message is 
(null) in Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value ()

**Comment by lodev09** [comment]
I think this PR fixes it
https://github.com/lodev09/react-native-true-sheet/pull/108

**Comment by KristijanKocev** [comment]
Amazing, thank you for the quick reply.
