### ISSUE TITLE
iOS build crashes

### ISSUE THREAD

**Issue by andreirat** [lodev09/react-native-true-sheet#15]
I just installed the latest version and the iOS doesn't want to build anymore. I get the following log: 
<img width="455" alt="Screenshot 2024-04-28 at 17 02 56" src="https://github.com/lodev09/react-native-true-sheet/assets/17424445/e1300a72-950b-4cb8-817e-0c5af2ccbaa0">

`"@lodev09/react-native-true-sheet": "^0.11.0",`
`"react-native": "0.73.2",`

**Comment by lodev09** [comment]
@andreirat my bad. forgot to test it out on a fresh RN project.. should be fixed now.
Thank you!
