### ISSUE TITLE
Dimmed in Android

### ISSUE THREAD

**Issue by nicolascavallin** [lodev09/react-native-true-sheet#18]
When `dimmed` in Android is also dimmed the `StatusBar` and the `NavigationBar`

Is there a way to avoid it?

Thanks

**Comment by lodev09** [comment]
Hello.

Do you have a screenshot? This is a default behavior of the `BottomSheetDialog` on Android and there might be no simple way to avoid this.

**Comment by nicolascavallin** [comment]
Yup. 

The "physical buttons" are accessible, but seem hidden visually. 

Thanks for your answer, I'll try to find a way to solve it, i.e.: in Telegram when the Bottom Sheet is opened the navigation bar keeps as before opened. I'm not sure if they are using `BottomSheetDialog` but the app is native, so I assume they are using it or something similar

![telegram-cloud-photo-size-1-5030630658082451154-y](https://github.com/lodev09/react-native-true-sheet/assets/22961489/30430e10-8967-4350-8112-feaf4524d38f)

**Comment by nicolascavallin** [comment]
Yep, I tried it, but avoiding dimming the components behind the sheet are reachable by gestures, and I want to avoid that.

Thanks again! ❤️ 

Is this an issue that could be fixed in a future release? In that case, I'll keep the issue open, otherwise, I'll close it

**Comment by lodev09** [comment]
I doubt it unless you could provide a reproducible example in a fresh project. There's lots of android settings behind the scenes that might be affecting the behavior :(
