### ISSUE TITLE
 ERROR  Invariant Violation: requireNativeComponent: "TrueSheetView" was not found in the UIManager. 

### ISSUE THREAD

**Issue by izakrobles** [lodev09/react-native-true-sheet#2]
I am hoping I could get assistance with this or better understand why I am getting this error when trying to use this package.

The error is:

 ERROR  Invariant Violation: requireNativeComponent: "TrueSheetView" was not found in the UIManager.

This error is located at:
    in TrueSheetView (at TrueSheet.tsx:147)
    in TrueSheet (at map.tsx:164)
    in RCTView (at View.js:116)
    {another 20+ lines}
    
I have an expo managed project that also uses yarn as my package manager. I installed this package by running:
yarn add @lodev09/react-native-true-sheet

from what I am reading online this typically means I have to eject my build or something along those lines and I am wondering what the process is to get this working. I don't want to go through the hassle of prebuilding my environment then not do it right anyways. Any help would be greatly appreciated.

**Comment by lodev09** [comment]
Are you using Expo GO?

**Comment by lodev09** [comment]
If you're using Expo Go, this package won't work. You need to eject your project and use [Expo development builds](https://docs.expo.dev/develop/development-builds/introduction/) instead.

Tip:
The [example](https://github.com/lodev09/react-native-true-sheet/tree/main/example) folder here is actually using expo prebuild. You can use it as guid if you want.

Feel free to create new issue if this is not the case. Closing.

**Comment by lodev09** [comment]
I agree. https://github.com/lodev09/react-native-true-sheet/commit/04577d39d0c98cc720cd6bd6b0674de51813fdd2
