### ISSUE TITLE
[Bug]: lib has issues with fast refresh on expo app

### ISSUE THREAD

**Issue by wcastand** [lodev09/react-native-true-sheet#23]
https://github.com/wcastand/bug-true-bottom--androidsheet

after looking into, it looks like it only ignore the props after a fast refresh.
if i fully reload the app, it seems to take into account the values.
Seems to be an issue on both ios and android where changing values/props makes the app behave weirdly or ignore the new values and i have to fully reload the app.

using default expo starter with `prebuild` to add the lib.

**Comment by lodev09** [comment]
Hey @wcastand.. what prop are you trying to modify on-the-fly specifically? I don't see issue on the provided example.
