### ISSUE TITLE
Example showing Footer with extra space on Pixel 6a

### ISSUE THREAD

**Issue by haivle** [lodev09/react-native-true-sheet#24]
Hi @lodev09 , when I try to run the example project on google pixel 6a, it shows me extra space of footer like this. Can you help me to take a look? It is happening on all examples: TrueSheet, ScrollView etc

<img width="304" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/52659811/03c43423-7590-4ebc-8643-ebf13cba7f20">

<img width="305" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/52659811/07a5e9ce-9f86-4bb8-8f84-50141cbedb25">

**Comment by lodev09** [comment]
Thanks for checking. I'll take a look later

**Comment by lodev09** [comment]
@haivle what emulator and API version is this? The pixel 6a from android studio seems different and I can't replicate it.

**Comment by haivle** [comment]
This is mine 
<img width="304" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/52659811/d0b144c5-ac71-4d8f-a2df-9ce22a024825">

**Comment by haivle** [comment]
I tested on 
- Pixel 6a: API 33, 34 the bug always happen
- Pixel 7: API 33, it does not happen

**Comment by lodev09** [comment]
Do you have custom setting on that emulator? My Pixel 6a looks different:
<img width="446" alt="Screenshot 2024-05-23 at 04 34 35" src="https://github.com/lodev09/react-native-true-sheet/assets/6686328/b2badb06-2986-4c99-8d9e-9773669322b7">

I think it has something to do with that bar at the top

**Comment by haivle** [comment]
hmm, i am just using a default emulator

<img width="1093" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/52659811/efccf756-5844-4354-8ae7-63bef90fc41e">

<img width="1084" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/52659811/beeee643-fea4-4152-8daf-4b7c7fca1735">

Properties
avd.ini.displayname              Pixel 6a API 33
avd.ini.encoding                 UTF-8
AvdId                            Pixel_6a_API_33
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile      
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:437310fd48ee977d023133a2babae359
hw.device.manufacturer           Google
hw.device.name                   pixel_6a
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   420
hw.lcd.height                    2400
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       2048
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         33
image.sysdir.1                   system-images/android-33/google_apis_playstore/arm64-v8a/
PlayStore.enabled                true
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google Play
tag.id                           google_apis_playstore
vm.heapSize                      256

**Comment by haivle** [comment]
here is what it looks like on my pixel 7 emulator, same as ur 6a's status bar

<img width="392" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/52659811/1947a622-52d7-41c2-948b-68ea20988d34">

**Comment by lodev09** [comment]
Ah.. it looks like this is a setting on the emulator itself:
https://stackoverflow.com/a/77808658/3685987

**Comment by haivle** [comment]
is that something we can fix, to make the bottom padding independent from that `cutout` settings?

**Comment by lodev09** [comment]
I'm looking into it :)

**Comment by lodev09** [comment]
Created PR.. can you test on your end? https://github.com/lodev09/react-native-true-sheet/pull/25

**Comment by haivle** [comment]
Tested, looking good now. Thanks for your quick support
