### ISSUE TITLE
Ability to open sheet on mount

### ISSUE THREAD

**Issue by ljukas** [lodev09/react-native-true-sheet#28]
Right now there is no real way to mount the sheet in opened state. We have to open it programmatically. 

A prop like `openOnMount` would be nice so the sheet opens automatically when mounted to. I personally want to use this so I can have a route that just have the TrueSheet and it opens when navigating to that screen.

Right now I can do a slight workaround like:

```
 const hasMounted = useRef(false);

  useEffect(() => {
    setTimeout(() => {
      if (hasMounted.current) return;
      hasMounted.current = true;
      handleOpen();
    }, 1000);
  }, []);
  ```
   Which works but does not feel very good

**Comment by lodev09** [comment]
I agree, timeout there is kinda weird.

As an alternative, if you're using `react-navigation`, you can subscribe to `transitionEnd` event so the sheet will show after the screen is shown.

**Comment by lodev09** [comment]
Or if you want to open it without waiting for the screen to be shown, use `useFocusEffect` instead.

**Comment by ljukas** [comment]
Using `useFocusEffect` does not work:

<img width="463" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/11976354/6080c828-96f7-42b8-8b9f-c08be420e67a">

<img width="655" alt="image" src="https://github.com/lodev09/react-native-true-sheet/assets/11976354/e7d05533-985a-4d61-9576-dde1723d16dd">

Hence why I had to use timeout :S

Subscribing to `navigation.addListener('focus')` gives the same error

**Comment by lodev09** [comment]
Ah I see.. Yeah, you'll have to use `transitionEnd ` then. The sheet needs to be under a ViewController for it to present. I don't know about your use case but why not just present the sheet without having to use a screen?

**Comment by ljukas** [comment]
I mean, I could of course do it as you say. Just using it regularly, mount on button press. What Im trying to accomplish though is to make it available via deepLinking. So in my case I would like the router: `/partner/[id]/contact` lead to this sheet. Which then is on its on route. In my prefered world react-navigation and this sheet would work together and  Screen in react-navigation would be able to render a TrueSheet. 

But I think I will just have to present it without the use a of a screen

**Comment by lodev09** [comment]
Ah.. What I would potentially do with that scenario is to use a route `param` instead of a dedicated empty screen. I think it's more "natural" and you don't have to navigate just to show a sheet.

Something like:
```ts
useEffect(() => {
  ;(async () =>  {
    if (id) {
      await sheet.current?.present()
      navigation.setParams({ id: undefined })
    }
  })()
}, [id])
```

**Comment by ljukas** [comment]
Yes that is a good solution as well.

TransitionEnd works though, but there is a bit a of delay when mounting and dismounting the screen so a param is probably best :)

Thanks for the help, and great lib you got here! Really like it!

**Comment by lodev09** [comment]
No problem. This got me thinking of adding a param on the `present` method to disable animation. Or something like an `initialIndex` so the sheet is shown by default. I'll add it when I get a chance :)

**Comment by ljukas** [comment]
initialIndex would be really great, so that it mounts as soon as possible without having to invoke the present function
