### ISSUE TITLE
Android: RectButton from 'react-native-gesture-handler' not working

### ISSUE THREAD

**Issue by gtokman** [lodev09/react-native-true-sheet#31]
## Bug

When using the RectButton from 'react-native-gesture-handler', the touch events are not working on Android. Switching to pressable or other built-in buttons works. 

## Repro
1. Make a project with: import { RectButton } from 'react-native-gesture-handler'
2. Launch on Android
3. Present sheet and try clicking the button

**Comment by lodev09** [comment]
Check out this troubleshooting [guid](https://sheet.lodev09.com/guides/troubleshooting#using-react-native-gesture-handler-on-android)

Let me know if that works

**Comment by gtokman** [comment]
Thanks @lodev09. Will keep you posted!
