### ISSUE TITLE
[CRASH] IOS still getting a crash even after last patch

### ISSUE THREAD

**Issue by wcastand** [lodev09/react-native-true-sheet#39]
Still getting a crash on reloading in dev on the expo app. i understand if you can't reproduce you can't fix it. just thought worth having an open issue if it happens to other people.

Seems to occur after a reload in dev mode (didn't build a production app yet to be 100% sure it's not happening in production app code though)

Expo: "^51.0.13"
true sheet: "^0.12.0"

Step to reproduce:

- open the app in dev mode
- hit R to reload the app
- navigate to a page with a TrueSheet in it (i don't need to try to open the sheet or anything)

screenshot of xcode crash if that can help
![Screenshot 2024-06-13 at 15 52 27](https://github.com/lodev09/react-native-true-sheet/assets/2178244/7e8bbbd1-bd77-46b8-8eef-7276c8192174)
![Screenshot 2024-06-13 at 15 52 38](https://github.com/lodev09/react-native-true-sheet/assets/2178244/ca3573db-d9d3-4755-86c1-883157e85d4d)
![Screenshot 2024-06-13 at 15 57 30](https://github.com/lodev09/react-native-true-sheet/assets/2178244/94b5d2a7-28b2-4ec7-9031-9adab9167e6b)
![Screenshot 2024-06-13 at 15 57 38](https://github.com/lodev09/react-native-true-sheet/assets/2178244/0a825108-f668-461a-8307-d70e1fd92b33)
![Screenshot 2024-06-13 at 15 57 47](https://github.com/lodev09/react-native-true-sheet/assets/2178244/5ebdd96a-b7b5-4208-9df9-37dd9cc6da55)
![Screenshot 2024-06-13 at 15 57 54](https://github.com/lodev09/react-native-true-sheet/assets/2178244/3809868a-e6d4-424b-94d5-9861ddba2765)

**Comment by lodev09** [comment]
Hey @wcastand, thanks for reporting.

Are you constantly experiencing this? Would be nice to have a reproducible example, or maybe a gist of the related code.

**Comment by wcastand** [comment]
yes it's consistent.

i will try a reproducible example but guessing it's related to my full setup and it's not a small one and i can't really share it since it's private repo.

i'll try my best for the gist. the screen where i manage to make it crash consistently on reload is my sign-in screen so i will give the best info and code possible.

using expo router with this arch:
```
- app
  _layout.tsx
  - (app)
    _layout.tsx
    sign-in.tsx
```

in the sign-in screen, the true sheet is part of the input as an optional hint.
the input in sign-in is not showing any hint so no trueSheet.

I have a `SafeAreaView`(in _layout.tsx) and It's inside a `ScrollView`(in Layout.tsx)

```typescript

// sign-in screen
  return (
    <Layout testID="signin-screen">
      <Stack.Screen options={{ title: t("HEADER_TITLE") }} />
      <KeyboardAvoidMarginView>
        <YStack flex={1} gap="$base">
          <Heading as="h3">{t("TITLE")}</Heading>
          <Input
            autoFocus
            name="email"
            control={control}
            label={t("EMAIL")}
            autoCapitalize={"none"}
            testID="signin-email-input"
            keyboardType="email-address"
            placeholder={t("PLACEHOLDER_EMAIL")}
          />
        </YStack>
        <YStack rowGap="$sm">
          {showSignUpButton && (
            <Button type="secondary" onPress={redirectToSignUp}>
              <Button.Text>{t("CREATE_PROFILE")}</Button.Text>
            </Button>
          )}
          <Button testID="signin-btn" onPress={handleSubmit(onSubmit)} disabled={isSubmitting}>
            <Button.Text>{t("RECEIVE_CODE")}</Button.Text>
          </Button>
        </YStack>
      </KeyboardAvoidMarginView>
    </Layout>
  )
```


the Input is a Controlled Input with `react-hook-form`

```typescript

// Input.tsx
  return (
    <>
      <Controller
        name={name}
        control={control}
        render={({ field: { onChange, onBlur, value }, fieldState: { error } }) => {
          const color = disabled ? "$neutral400" : error ? "$error400" : "$neutral900"
          const borderColor = disabled ? "$transparent" : error ? "$error400" : "$transparent"
          return (
            <YStack gap="$xsm" {...containerProps} opacity={disabled ? 0.4 : 1}>
              {(label || info || hint) && (
                <XStack jc={label ? "space-between" : "flex-end"} ai="flex-end">
                  {label && (
                    <YStack>
                      <Body fontWeight="$bold" color={color}>
                        {label}
                      </Body>
                      {sublabel && (
                        <Body as="body2" color={color}>
                          {sublabel}
                        </Body>
                      )}
                    </YStack>
                  )}
                  {info ? (
                    <Link type={error ? "red" : "primary"} onPress={openSheet}>
                      <Info />
                    </Link>
                  ) : (
                    hint && (
                      <Body as="body2" color={color}>
                        {hint}
                      </Body>
                    )
                  )}
                </XStack>
              )}
              <InputBase
                ref={myRef}
                onChangeText={(v) => onChange(transformOnChange ? transformOnChange(v) : v)}
                onBlur={onBlur}
                editable={!disabled}
                value={value}
                borderColor={borderColor}
                focusStyle={{ borderColor: color }}
                {...props}
              />
              {!hideErrorContainer && error && (
                <YStack position="relative" bg="white">
                  <Body as="body2" color="$error400">
                    {error?.message}
                  </Body>
                </YStack>
              )}
            </YStack>
          )
        }}
      />

      {info && (
        <BottomSheet name={`bottom_sheet_field_${name}`} ref={trueSheetRef}>
          <View gap="$base">{info}</View>
        </BottomSheet>
      )}
    </>
  )
```

**Comment by lodev09** [comment]
Ah.. the conditional rendering might be causing it.

```tsx
{info && (
  <BottomSheet name={`bottom_sheet_field_${name}`} ref={trueSheetRef}>
    <View gap="$base">{info}</View>
  </BottomSheet>
)}
```

Try it like this:

```tsx
<BottomSheet name={`bottom_sheet_field_${name}`} ref={trueSheetRef}>
  {info && <View gap="$base">{info}</View>}
</BottomSheet>
```

Alternatively, you could render a "placeholder" if you're worried about size changes on the fly.

I'm using TrueSheet on my project as a Select field as well and I don't see this issue happening. Rendering the sheet in the background is fine since it's handled natively.

**Comment by wcastand** [comment]
i already tried that and was still getting the crash :/

i will give it a second try just in case tho. i let you know if it works this time

**Comment by wcastand** [comment]
ok so rebuild the app with cleared cache and all to be safe this time when i test. so far could not reproduce the bug. will play with it a little bit longer but maybe it's solved.

**Comment by wcastand** [comment]
still getting some crash in the production app this time. mainly happens after an update is received and the app is reloaded, when i visit a screen with a true sheet, the app crashes.

can find the report of the crash 

![Screenshot 2024-07-01 at 10 30 44](https://github.com/lodev09/react-native-true-sheet/assets/2178244/d371807c-d87c-4c44-8fae-59f35708e51e)

**Comment by lodev09** [comment]
Yeah, there's some weird stuff going on with expo-updates. Reloading after update is basically the same as in dev mode hot reload. I'm not sure what's the proper fix for it since it's very hard to reproduce ;(

In this block:
https://github.com/lodev09/react-native-true-sheet/blob/329026d62e8c077aa1ae55e09d6d57dcc5fd6efd/ios/TrueSheetView.swift#L142-L147

Can you change it with this:
```swift
  func viewControllerDidChangeWidth(_ width: CGFloat) {
    guard let containerView, let uiManager = bridge?.uiManager else { return }

    let size = CGSize(width: width, height: containerView.bounds.height)
    uiManager.setSize(size, for: containerView)
  }
```

See if that fixes the problem.

**Comment by lodev09** [comment]
@wcastand PR #52. Try it and let me know if that fixes the issue

**Comment by wcastand** [comment]
it's on my production app, can't really use a git branch for testing? unless i'm missing something.

did you publish that branch to an npm beta version to install it? happy to try to reproduce on dev altho so far no luck on that side.

**Comment by wcastand** [comment]
can try to reproduce on dev app, but same as you super hard to reproduce and can't really make a prod version with a github branch :/

**Comment by wcastand** [comment]
so far since the update, it looks like we get no more crash on production app after an update reload. so looks like it did the job. thanks

we still get warning on other things, mostly when we want to open a sheet right after we nagivate to the screen, we get a warning saying it's not intanciated yet even if we check the ref before calling. if i can manage to make a repro i will make a ticket.

**Comment by lodev09** [comment]
> we still get warning on other things, mostly when we want to open a sheet right after we nagivate to the screen, we get a warning saying it's not intanciated yet even if we check the ref before calling. if i can manage to make a repro i will make a ticket.

Ah, that's pretty normal. You can use the [`initialIndex`](https://sheet.lodev09.com/reference/props#initialindex) instead if you want to present the sheet right after navigating.

**Comment by wcastand** [comment]
i have a weird behavior when i try to use initialIndex to open the sheet when navigating to the screen

want me to open an other issue for it?
https://github.com/lodev09/react-native-true-sheet/assets/2178244/91765a56-9eb6-4a8d-a3e6-e534c19e1c2b

**Comment by lodev09** [comment]
@wcastand can you try with `isFocused`?

**Comment by wcastand** [comment]
what do you mean by `isFocused`? 
is this a props not documented? can't find anything in the docs

**Comment by lodev09** [comment]
I think the reason why you're getting that weird issue is that the screen is not yet "fully" rendered. You could try `react-navigation` `useIsFocused` hook to render the sheet when the screen is focused.

e.g.
```
isFocused = useIsFocused()

return (
  {isFocused && (
    <TrueSheet initialIndex={0}>...</TrueSheet>
  )}
)

**Comment by lodev09** [comment]
okay I tried `useIsFocused` and it looks like it's still happening. What's interesting is that it works fine on modal screens. Unfortunately, this has something to do with `react-native-screen`, package used by `react-navigation`, so I don't have control over this issue, natively. 😢 

What you can do to fix it is used `react-navigation`'s [`transistionEnd`](https://reactnavigation.org/docs/native-stack-navigator/#transitionend) lifecycle event. This will trigger when the screen is fully shown

**Comment by lodev09** [comment]
Yep, worked for me too 👍

**Comment by wcastand** [comment]
also kind of related but because we use sheet as boolean (open/close) and not multiple size, i was looking for a `open` props or something to open on mount. never thought about initialIndex for it. if there is a FAQ or guide section, would be a good idea to mention and put that info out there.

like 
`How to open the sheet on mount ?`
and a little guide to use initialIndex and what we talked about above maybe?

do you have a place for this kind of stuff on the site/repo?

**Comment by lodev09** [comment]
yep https://github.com/lodev09/react-native-true-sheet/pull/59

**Comment by wcastand** [comment]
amazing so fast ahah !!

**Comment by rranjan14** [comment]
Tried with latest version on expo@53, react-navigation v7 and react-native-screens@4.11.1 where it's crashing on ios - https://github.com/lodev09/react-native-true-sheet/issues/205
