### ISSUE TITLE
'icons' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by harbolaez** [lodev09/react-native-true-sheet#40]
Running on react-native "react-native": "0.72.8" and with minimumIos Verson set to 14, getting error on `extension UIBlurEffect`

<img width="1029" alt="Screenshot 2024-06-14 at 4 43 41 PM" src="https://github.com/lodev09/react-native-true-sheet/assets/13140872/9e152389-b2a2-48fe-a2f4-fd8f745f8cb6">

**Comment by lodev09** [comment]
@harbolaez you need to upgrade your RN version to at least `0.73`. See [this issue](https://github.com/facebook/react-native/issues/41053#issuecomment-1770292532).

**Comment by lodev09** [comment]
In context, TrueSheet uses `min_ios_version_supported` pod config from RN which will ultimately use IOS 12.4.
