### ISSUE TITLE
Add an ability to display BottomSheetComponent from the top of the screem

### ISSUE THREAD

**Issue by VladyslavMartynov10** [lodev09/react-native-true-sheet#45]
Hey @lodev09 !

Thanks again for such a cool package with native transitions. Is it possible to add a new prop, `inversed`, which will allow rendering Bottomsheet components starting from the top of the screen (top inset)? Right now, the library only supports the default slide-up effect from bottom to top. I didn’t find this functionality in other non-native libraries, but I believe it’s possible to add it here.

**Comment by lodev09** [comment]
Hey, thanks for the feedback.

Regarding your request, there's no simple way of achieving it natively. It's certainly possible but requires lots of custom code to achieve. I'm trying to keep this package simple as possible.

You could, however, create a custom one using reanimated.
