### ISSUE TITLE
Stack Navigator Not Displaying in TrueSheet Component

### ISSUE THREAD

**Issue by whynotly** [lodev09/react-native-true-sheet#46]
Description:
When attempting to use a StackNavigator within the TrueSheet component, the sheet displays a white screen instead of the expected navigation content. This issue occurs on both iOS and Android platforms.

Steps to Reproduce:

Create a new React Native project.
Install @lodev09/react-native-true-sheet and @react-navigation/stack.
Set up a basic StackNavigator with a few screens.
Include the StackNavigator inside the TrueSheet component.
Present the TrueSheet.
Expected Behavior:
The StackNavigator should display its initial screen within the TrueSheet component.

Actual Behavior:
The TrueSheet displays a white screen, and the StackNavigator content is not visible.

Example Code:

javascript
Copy code
import React, { useRef } from 'react';
import { View, Button } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { TrueSheet } from '@lodev09/react-native-true-sheet';

const Stack = createStackNavigator();

const HomeScreen = ({ navigation }) => (
  <View>
    <Button
      title="Go to Details"
      onPress={() => navigation.navigate('Details')}
    />
  </View>
);

const DetailsScreen = () => (
  <View>
    <Text>Details Screen</Text>
  </View>
);

const App = () => {
  const sheet = useRef<TrueSheet>(null);

  const present = async () => {
    await sheet.current?.present();
  };

  return (
    <View>
      <Button onPress={present} title="Present" />
      <TrueSheet ref={sheet} sizes={['auto', 'large']} cornerRadius={24}>
        <NavigationContainer>
          <Stack.Navigator initialRouteName="Home">
            <Stack.Screen name="Home" component={HomeScreen} />
            <Stack.Screen name="Details" component={DetailsScreen} />
          </Stack.Navigator>
        </NavigationContainer>
      </TrueSheet>
    </View>
  );
};

export default App;
Environment:

Expo version: 51
Platform: iOS/Android
Additional Context:

The issue might be related to how the TrueSheet component handles nested navigation components.
The problem persists despite various attempts to style or wrap the StackNavigator component.
Possible Solution:
Any guidance or fixes on ensuring the StackNavigator displays correctly within the TrueSheet component would be greatly appreciated.

Thank you for your attention to this issue.

**Comment by lodev09** [comment]
TrueSheet doesn't have first-class support for react-navigation, yet. As you mentioned, react-navigation has its own native implementation and doesn't play well with TrueSheet.

You can still use react-navigation with TrueSheet but it's not possible to contain the stack inside the sheet.

**Comment by aramikuto** [comment]
@lodev09 Thank you for this library! I noticed the docs mention React Navigation integration now, but when I tried mounting a native stack navigator inside a TrueSheet, the content didn't render.

Just to confirm: does React Navigation integration work only for presenting the sheet from navigation, but embedding/mounting React Navigation navigators inside the sheet isn't supported?

**Comment by lodev09** [comment]
@aramikuto correct. you can only put a stack navigator at the first child of the sheet navigator or specify it by `initialRouteName`. But this will be sheet's main screen that it can present on and not a screen that you can render in the sheet.

See [navigation guide](https://sheet.lodev09.com/guides/navigation#sheet-navigator) for example.

**Comment by mgray88** [comment]
@lodev09 Is something like that planned? Or, and I haven't tried this yet with this library, but it's how I do it currently with manually created modal sheets, would `NavigationIndependentTree` work to accomplish this?

**Comment by lodev09** [comment]
@mgray88 not planned because this is a limitation. it's by design with the navigators -- you will get error if you render navigator inside another navigator. They have their own modal/formSheet support so they can do whatever they want, truesheet is just 3rd party.

> would NavigationIndependentTree work to accomplish this?

You can try this but i'm not even sure if expo-router supports this. Also, you would need separate navigation, etc. I believe gorhom bottom sheet did the same thing before, not sure on the current version.
