### ISSUE TITLE
Footer Component weird behaviour on Android

### ISSUE THREAD

**Issue by PopJoestar** [lodev09/react-native-true-sheet#47]
Hello, as the title says the FooterComponent is displayed well on iOS but on Android, it is buggy. Can someone help me?
**iOS**
![simulator_screenshot_DB5CEB35-034E-4668-83EC-0D58622058CA](https://github.com/lodev09/react-native-true-sheet/assets/66442553/54aa8dec-3ad0-4908-a775-efc954676cb0)

**Android**
![448802456_801310865439679_3750398373025187280_n](https://github.com/lodev09/react-native-true-sheet/assets/66442553/fac40d40-859f-48ce-be8e-b02eafbd8f68)

Here is the part of my code for this
<img width="740" alt="Screenshot 2024-06-29 at 16 06 37" src="https://github.com/lodev09/react-native-true-sheet/assets/66442553/ef93d6d4-7627-4377-9426-2849bd767e41">
d940)

**Comment by lodev09** [comment]
Try to use `margin` instead of `bottom` on your `saveContainer` style.

**Comment by PopJoestar** [comment]
I have already tried margin and padding but the same behavior 😔 the only value that worked was `bottom: -160` for Android only. Still, this component is a wrapper that I use for every sheet with a Save footer button in my application, and the `bottom: -160` only works for a few of those sheets.

**Comment by lodev09** [comment]
Can you use simple `View` instead of `GestureHandlerRootView`?

**Comment by PopJoestar** [comment]
Same behaviour

**Comment by lodev09** [comment]
Okay, that's weird... can you try to wrap `children` with a `View`? If that doesn't work, please create a reproducible example that I can look at.

**Comment by PopJoestar** [comment]
Same behavior. I will give you an example asap

**Comment by PopJoestar** [comment]
@lodev09 here you go sir https://github.com/PopJoestar/trusheetExample

**Comment by lodev09** [comment]
I see the issue. It looks like a regression bug from `v0.12`

**Comment by lodev09** [comment]
PR #48, give it a try and let me know if that fixes your issue. Thanks!

**Comment by PopJoestar** [comment]
Thanks for your reactivity, it works well on Android and iOS now  🚀🎉

**Comment by a-eid** [comment]
had this issue today, works perfectly after the upgrade, thank you @lodev09
