### ISSUE TITLE
[iOS]: Attempt to present sheet on top of an existing sheet

### ISSUE THREAD

**Issue by KirillCustom** [lodev09/react-native-true-sheet#5]
On iOS, when you try to open a sheet on top of an existing sheet, an error appears in the console:

`Attempt to present <TrueSheet.TrueSheetViewController: 0x11829f800> on <UIViewController: 0x10900eb10> (from <RNSScreen: 0x117dbf400>) which is already presenting <TrueSheet.TrueSheetViewController: 0x11a0b9200>.`

Does this library support multiple sheets, as in Android?

**Comment by lodev09** [comment]
@KirillCustom define the sheet within the parent sheet. Or dismiss the presented sheet first before opening another one. The former has better UX imo.

```tsx
<TrueSheet>
  <Button onPress={() => sheet2.current?.present()}
  <TrueSheet ref={sheet2}>
    // ...
  </TrueSheet>
</TrueSheet>
```
Example:
![2024-04-19 21 52 06](https://github.com/lodev09/react-native-true-sheet/assets/6686328/ac199a48-0520-40ad-b805-2ddff2cb475f)
