### ISSUE TITLE
Android Edge to Edge support.

### ISSUE THREAD

**Issue by a-eid** [lodev09/react-native-true-sheet#50]
Sheet doesn't seem to run in edge to edge mode on android even though my app does. 
so basically I am able to draw content below the android Navigation bar, however the sheet footer avoids that by default.

the sheet it self seem to be drawing under the NaviationBar, but not the FooterComponent.

**Comment by lodev09** [comment]
Can you create a reproducible example? Handling position in android was a pain, might need to add some conditions when edge-to-edge is enabled. Haven't tried that yet.

**Comment by a-eid** [comment]
> Can you create a reproducible example? Handling position in android was a pain, might need to add some conditions when edge-to-edge is enabled. Haven't tried that yet.

will do

**Comment by lodev09** [comment]
I'm going to close this and reference it all on #56. Footer in android right now needs work -- it's a bit hacky and I'm not really happy about it
