### ISSUE TITLE
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by wogno** [lodev09/react-native-true-sheet#53]
<img width="331" alt="Capture d’écran 2024-07-01 à 17 27 52" src="https://github.com/lodev09/react-native-true-sheet/assets/31076843/03a5fb59-465b-423c-92cf-e3b6c9f5c9bb">

brighless and new architecture are enabled

"@lodev09/react-native-true-sheet": "^0.12.3",
 "react-native": "0.74.2",
<img width="799" alt="Capture d’écran 2024-07-01 à 17 31 08" src="https://github.com/lodev09/react-native-true-sheet/assets/31076843/ddf5f5e2-5274-4705-be6a-80b213760737">

**Comment by lodev09** [comment]
Not yet supported. Tracked [here](https://github.com/lodev09/react-native-true-sheet/discussions/20)
