### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by yakshao** [lodev09/react-native-true-sheet#54]
I want to try trueSheet but I am facing a problem. 

**Render Error 'TrueSheetView' was not found in the UIManager.**

I am using the latest Expo. I tried installing it through Expo and tried an older version too, but I am still getting this error

**Comment by lodev09** [comment]
Are you using Expo GO?

**Comment by yakshao** [comment]
> Are you using Expo GO?

Yes..

**Comment by lodev09** [comment]
Expo GO is not supported. See [installation guide](https://sheet.lodev09.com/install). Use CNG instead

**Comment by yakshao** [comment]
Sorry, I read almost all the documentation and managed to miss it somehow... : )
