### ISSUE TITLE
FooterComponent is hidden by keyboard

### ISSUE THREAD

**Issue by PopJoestar** [lodev09/react-native-true-sheet#55]
Hello ! On Android, the FooterComponent is hidden by the keyboard when using a TextInput inside Truesheet (even when keyboardMode is pan or resize). Does someone has a solution for this?
<img width="362" alt="Screenshot 2024-07-02 at 19 21 36" src="https://github.com/lodev09/react-native-true-sheet/assets/66442553/7f5ac19b-f6e7-46e5-93c8-ca0ec74e7384">

Here is a reproducible example: https://github.com/PopJoestar/trusheetExample

**Comment by lodev09** [comment]
`FooterComponent` is flunky at this time. If you're not dealing with scrollable sheet, you can just append it at the content (do NOT float).

**Comment by lodev09** [comment]
Also, make sure the `keyboardMode` is `resize`

**Comment by lodev09** [comment]
<img width="355" alt="Screenshot 2024-07-04 at 06 01 34" src="https://github.com/lodev09/react-native-true-sheet/assets/6686328/46b1730d-e3f9-450e-9894-2b2c2278abff">
