### ISSUE TITLE
Keyboard overlaps modal on older Androids

### ISSUE THREAD

**Issue by marcosrdz** [lodev09/react-native-true-sheet#60]
With Android API 29. Works automatically on API 34.

<img width="352" alt="Screenshot 2024-07-04 at 3 47 17 PM" src="https://github.com/lodev09/react-native-true-sheet/assets/4793122/2b2e8553-911e-45a2-b64b-052a55fd18cd">

**Comment by lodev09** [comment]
I think that's fine. Not that big of a deal imo. FWIW, IOS doesn't even support sized sheets below IOS 15 so it's fair 😅

Feel free to open PR if you can find a fix for it. Thank you!
