### ISSUE TITLE
keyboard reappear, input refocus after dismissing the bottom sheet. option to disable this behavior

### ISSUE THREAD

**Issue by bryanltobing** [lodev09/react-native-true-sheet#62]
sometimes, it is expected that the keyboard and input fields refocus after the bottom sheet is dismissed. however, I also have a use case where I don't want that. 

for example, when dismissing the bottom sheet and then navigating to another screen, I don't want the keyboard and input to reappear and refocus like this.

https://github.com/lodev09/react-native-true-sheet/assets/46083126/296e0e91-b1db-4f4d-ad91-e787febf00c2

In `Gorhom Bottom Sheet`, I need to handle all this manually by calling `Keyboard.dismiss()`. so, I'm glad this library handles it automatically. I tried using `Keyboard.dismiss()` in TrueSheet before presenting it, but it doesn't do anything.

it would be nice to have the option to opt in or opt out of this behavior.

**Comment by lodev09** [comment]
I think this is normal behavior since the input is still in focus when you presented the sheet. Did you try blurring the input instead?

```tsx
input.current?.blur()
```
