### ISSUE TITLE
Support safe area on iOS

### ISSUE THREAD

**Issue by gtokman** [lodev09/react-native-true-sheet#63]
It would be helpful to support safe area on iOS. It's hard to get the content to do so without setting padding everywhere.

docs: https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area

**Comment by lodev09** [comment]
Yeah it does support safe area natively.. however, I intentionally opt-out with it for consistency. RN itself doesn't support safe area so I feel like it's the dev's responsibility to implement it.

Some users want Safe Area but some might not. This keeps the library flexible and extendable .
