### ISSUE TITLE
iOS Close/Dismiss button

### ISSUE THREAD

**Issue by marcosrdz** [lodev09/react-native-true-sheet#65]
https://developer.apple.com/design/human-interface-guidelines/sheets

I could be wrong but is there an option to display that apparently default" close X button so I dont have to manually code one?

**Comment by lodev09** [comment]
There's no direct property to enable/add it. You'll have to create a custom one natively so there's no really real advantage to expose it as a prop.

Unless I'm missing something, feel free to paste here.

**Comment by marcosrdz** [comment]
> There's no direct property to enable/add it. You'll have to create a custom one natively so there's no really real advantage to expose it as a prop.
> 
> 
> 
> Unless I'm missing something, feel free to paste here.

I probably misread the docs but I read that wrapping the sheet in a ui navcontroller gives the X for free.
The advantage would be not having to code one and for accessibility
