### ISSUE TITLE
systemMaterialDark is only available in ios 13.0 or newer expo sdk49

### ISSUE THREAD

**Issue by bryanltobing** [lodev09/react-native-true-sheet#67]
i got this error when building ios app with expo sdk49 and true sheet `v0.12.3`

![image](https://github.com/user-attachments/assets/c78fa19d-c80b-45fd-8bdb-c3bbe29f539b)

i already set my minimum deployment target to 13 and even tried above version, but still got the same error,

any idea why this is happen?

repo to reproduce:

https://github.com/bryanltobing/expo49-truesheet-error

steps:
- clone and yarn install repo
- npx expo prebuild -p ios
- npx expo run:ios

seems like the issue doesn't appear in expo 50 and above. but i need this to work in expo 49 since we are still unable to upgrade at the moment

**Comment by lodev09** [comment]
The library follows minimum IOS version set by RN.
https://github.com/lodev09/react-native-true-sheet/blob/643f4e8f39aabfe1403de74042b25bdb392f18ce/TrueSheet.podspec#L14

I guess I'll have set it explicitly to IOS 13 :/. However, I would suggest you upgrade to expo 50 soon :)
