### ISSUE TITLE
Navigation bar color change when opening sheet on Android

### ISSUE THREAD

**Issue by SickanK** [lodev09/react-native-true-sheet#69]
**Description**
When opening a sheet on Android, the navigation bar changes to a gray color. If the sheet has a white background, this can look out of place. A possible solution could be to either keep the navigation bar's original color or add an option to set a custom color. I'm not sure what's technically feasible in this case.

**Steps to Reproduce**
1. Set up a project using react-native-true-sheet on Android
2. Open a sheet

**Environment**
react-native-true-sheet version: 0.12.3
React Native version: 0.74.3
React Native Gesture Handler version: 2.16.1
Platform: Android

**Images**
![Screenshot_20240719-202106](https://github.com/user-attachments/assets/95d44ae3-37bb-4e56-ad2a-066c95267a85)
![Screenshot_20240719-202325](https://github.com/user-attachments/assets/3ab650a7-9578-4f39-92d7-f97c0d504e41)

**Comment by lodev09** [comment]
Unfortunately, the lib doesn't have control over this behavior. This is somehow the default behavior of android's native bottom sheet. :(

**Comment by a-eid** [comment]
@lodev09 isn't there a way to avoid this with the help of @zoontek edge to edge package ?
