### ISSUE TITLE
Android Edge to edge support

### ISSUE THREAD

**Issue by SickanK** [lodev09/react-native-true-sheet#72]
Yesterday, I created ticket #69 regarding a color change in the bottom navigation bar. Upon further investigation, I realized that the color change was due to the backdrop showing through the transparent color I had set for the navigation bar. A similar issue with edge-to-edge on android was previously reported in ticket #50, which has since been closed.

Description:
When using react-native-unistyles, which automatically sets Android to edge-to-edge mode, the sheet floats above the navigation bar. I've also set the color of the navigation bar to transparent for the effect to be noticeable. In the provided reproduction, you can see the text showing through the navigation bar.

Reproduction: https://github.com/SickanK/react-native-true-sheet-edge

Images:
![Screenshot_20240721-030458](https://github.com/user-attachments/assets/85080068-773a-4111-a7a9-ba802a63dc3a)
![Screenshot_20240721-030350](https://github.com/user-attachments/assets/2bd74789-4bfa-4494-aa64-236c4cd0b636)

**Comment by lodev09** [comment]
Okay. thanks for investigating.. Looks like I just need the sheet to detect if edge to edge is enable. I have yet to explore on that feature on Android..

I'm kind of occupied at the moment, but I'm open to PRs :)

**Comment by SickanK** [comment]
I gave it a try for an hour, but my skills aren't up to the task. Looks like I'll just have to wait for now! :)

**Comment by lodev09** [comment]
@SickanK no worries.. I can understand, android doesn't make things easy like IOS :D

**Comment by lodev09** [comment]
I tried looking for solution on this but couldn't find one that works. I honestly think this is an issue with Android bottom sheet itself lol.

I'll pin this and maybe someone that knows android can fix this for us 😅

**Comment by a-eid** [comment]
@lodev09 there is no way to detect edge-to-edge on android, however you could add it as an option prop to the true sheet component. 

checkout [react-native-controller](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/recipes/platform-differences#android) docts.

[RN unistyle 1](https://www.unistyl.es/reference/edge-to-edge/) 
[RN unistyle 2](https://www.unistyl.es/reference/faq/#my-android-app-is-not-edgetoedge-or-insets-are-incorrect)

**Comment by lodev09** [comment]
Yes that's what I thought, by using a prop boolean. My main issue is that I couldn't find a working could that moves the sheet at the bottom edge.

**Comment by hirbod** [comment]
@kirillzyusko can you maybe help out? I just toggled your `navigationBarTranslucent` and everything works fine, but breaks with this library. You have lot's of knowledge with Edge to Edge, maybe you can add support into this library.

**Comment by kirillzyusko** [comment]
@hirbod I had only a brief look at the code. It looks like for showing a sheet we show a dialog and then attach `RootSheetView`. But on top of my head a dialog doesn't know anything about the edge-to-edge mode (same problem with `Modals` in `react-native` and overall the android part looks very similar to `Modal` implementation on Android) and it will not be stretched to the full window by default.

A potential solution would be measuring `rootView` of main `Activity` and then force `dialog` to stretch to these sizes. In this case it should work in both variants - `edge-to-edge` and not `edge-to-edge` 🤷‍♂️ 

@lodev09 would you mind do some experiments with forcing the dialog to stretch to full window size and let us know the result? 👀 I'm keen to help, but don't have too much free time at the moment (unfortunately).
We can also sync up on discord if you want 😊

**Comment by lodev09** [comment]
Hey @kirillzyusko. Thanks for looking!

The app doesn't really need to automatically determine if edge-to-edge is enabled -- we can put this burden to the user and add a prop for the TrueSheet to know if edge-to-edge is enabled 😅

However, I'm missing something to make the actual BottomSheetDialog to popup at the edge of the screen. Assuming that edge-to-edge is enabled.

I did a second googling and it looks like I might just be missing the style requirement for the `navigationBarColor`. Doc says it needs to be `transparent`. I'll take a look more this week and try it out.

**Comment by lodev09** [comment]
> I probably can open a PR if you want 🙂

@zoontek that would be awesome!

**Comment by zoontek** [comment]
@lodev09 PR opened: https://github.com/lodev09/react-native-true-sheet/pull/103

**Comment by lodev09** [comment]
Thanks @zoontek! I'll do the docs at a separate PR before release.
Closing 💪
