### ISSUE TITLE
Android background dimmer is above android home bar controls

### ISSUE THREAD

**Issue by ljukas** [lodev09/react-native-true-sheet#79]
See the difference at the bottom of the screen on android vs ios

![image](https://github.com/user-attachments/assets/3edf20f1-121a-4245-a3e8-4701b1139482)
![image](https://github.com/user-attachments/assets/1d8af22d-e660-4b6b-aa28-ab83164c31f2)

This is the same sheet opened on ios and android, you can see that on android the dimmer effect goes above the bottom home controls on android

**Comment by lodev09** [comment]
@ljukas looks like related to #72. Closing
