### ISSUE TITLE
[feature-request] onBackdropPress callback

### ISSUE THREAD

**Issue by whalemare** [lodev09/react-native-true-sheet#91]
First of all, thank you for your library.

I have an issue, where TrueSheet with focused TextInput inside, close whole TrueSheet instead of just remove focus from TextInput, when user press on backdrop.

Can you please add some `onBackdropPress` function with default behavior that close TrueSheet, but can be overrides?

Video with example, how it looks like

https://github.com/user-attachments/assets/f90deed8-bd44-40cf-ba4d-c29e56bd86dc

**Comment by lodev09** [comment]
You can conditionally set [`dismissible`](https://sheet.lodev09.com/reference/props#dismissible) prop when keyboard appears.

Let me know if that works.
