### ISSUE TITLE
Pressable not responding inside True Sheet with New Architecture

### ISSUE THREAD

**Issue by akuul** [lodev09/react-native-true-sheet#95]
Hello, I'm having an issue that might be related to React Native itself actually in a way, but want to see if there is some insight available. 

Pressable inside TrueSheet doesn't respond to clicks. You can find the minimal repro code below. Pressables outside TrueSheet do respond to clicks. Touchables like `TouchableWithoutFeedback` and similar from RNGH package do respond to clicks. 

I have also noticed strange behaviour if I use `Button` component inside `TrueSheet` when `sizes={['auto', 'large']}`. onPress dismiss() enlarges the sheet instead of closing. Passing `sizes={['auto']}` closes, but console.logs aren't being called as well as dismiss() doesn't seem to be actually called.

This behaviour starts working after disabling New Architecture so it might be related to React Native itself.

## Expected Behavior
Pressable should be responding to clicks

## Actual Behavior
Pressable does not respond to click, but RNGH Touchables do.

## Steps to Reproduce the Problem

```typescript
  // Present the sheet ✅
  const present = async () => {
    await sheet.current?.present();
    console.log('horray! sheet has been presented 💩');
  };

  // Dismiss the sheet ✅
  const dismiss = async () => {
    await sheet.current?.dismiss();
    console.log('Bye bye 👋');
  };

  return (
     <View>
      <Pressable onPress={present}>
        <CText>BUTTON</CText>
      </Pressable>
      <TrueSheet ref={sheet} sizes={['auto', 'large']} cornerRadius={24}>
        <Pressable
          onPress={dismiss} <--- Not doing anything
          style={{ backgroundColor: 'red', height: 200 }}
        />
      </TrueSheet>
    </View>
  );
  ```

## Specifications

  - TrueSheet Version: 0.13.0
  - Platform: iOS
  - React Native: 0.75.4 New Architecture
  - RNGH: 2.20.0

**Comment by lodev09** [comment]
Hey, thanks for reporting. Please see this discussion for New Arch support: https://github.com/lodev09/react-native-true-sheet/discussions/20

Closing this one for now.

**Comment by ShivamJoker** [comment]
@lodev09 facing this issue when I use actual Android device with finger, ADB touches and devices seem to work fine.
Can we reopen this?

**Comment by fukuli053** [comment]
@lodev09 Hi, The problem still persists. I am using Expo SDK 52 with new arc. I can not touch any pressable components or touchable components in TrueSheet. I also wrapped these with GestureHandlerRootView.
