### ISSUE TITLE
Don't calculate current height

### ISSUE THREAD

**Issue by seyedmostafahasani** [lodev09/react-native-true-sheet#99]
First, I want to say thank you for this library. I really like it!

I'm using the library as shown below, but when I open the bottom sheet, it doesn't display at the expected height. I expected the bottom sheet to open at its current height.

```
<TrueSheet ref={trueSheetRef}>
        <View style={{width: 100, height: 100, backgroundColor: 'red'}} />
        <View style={{width: 100, height: 500, backgroundColor: 'green'}} />
</TrueSheet>
```

https://github.com/user-attachments/assets/2bfe39a3-e4b8-47a6-b262-b42ead788684

**Comment by lodev09** [comment]
Hey. Checkout [`sizes`](https://sheet.lodev09.com/reference/props#sizes) prop. Default is `['medium', 'large']`. Set it to `['auto']`

**Comment by seyedmostafahasani** [comment]
@lodev09 
Thank you!
